name: env_jsa
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - libffi=3.4.4
  - libmpdec=4.0.0
  - libzlib=1.3.1
  - openssl=3.0.18
  - pip=25.2
  - python=3.13.9
  - python_abi=3.13
  - setuptools=80.9.0
  - sqlite=3.50.2
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - tree-sitter==0.25.2
      - tree-sitter-java==0.23.5
