name: env_jsa
channels:
  - defaults
dependencies:
  - libffi=3.4.4
  - openssl=3.0.18
  - vc14_runtime=14.44.35208
  - xz=5.6.4
  - wheel=0.45.1
  - python=3.13.9
  - libzlib=1.3.1
  - ucrt=10.0.22621.0
  - vs2015_runtime=14.44.35208
  - pip=25.2
  - tk=8.6.15
  - setuptools=80.9.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - tzdata=2025b
  - python_abi=3.13
  - sqlite=3.50.2
  - zlib=1.3.1
  - vc=14.3
  - libmpdec=4.0.0
prefix: C:\Users\Think\anaconda3\envs\env_jsa
